version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - setori_bundle:/app/vendor/bundle
      - setori_node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    platform: linux/arm64/v8
    # platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - setori-db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  setori-db-volume:
    driver: local
  setori_bundle:
    driver: local
  setori_node_modules:
    driver: local
  